/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TentangKamiRouteImport } from './routes/tentang-kami'
import { Route as RelawanRouteImport } from './routes/relawan'
import { Route as MitraRouteImport } from './routes/mitra'
import { Route as MerchandiseRouteImport } from './routes/merchandise'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoStoreRouteImport } from './routes/demo/store'

const TentangKamiRoute = TentangKamiRouteImport.update({
  id: '/tentang-kami',
  path: '/tentang-kami',
  getParentRoute: () => rootRouteImport,
} as any)
const RelawanRoute = RelawanRouteImport.update({
  id: '/relawan',
  path: '/relawan',
  getParentRoute: () => rootRouteImport,
} as any)
const MitraRoute = MitraRouteImport.update({
  id: '/mitra',
  path: '/mitra',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchandiseRoute = MerchandiseRouteImport.update({
  id: '/merchandise',
  path: '/merchandise',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoStoreRoute = DemoStoreRouteImport.update({
  id: '/demo/store',
  path: '/demo/store',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/merchandise': typeof MerchandiseRoute
  '/mitra': typeof MitraRoute
  '/relawan': typeof RelawanRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/merchandise': typeof MerchandiseRoute
  '/mitra': typeof MitraRoute
  '/relawan': typeof RelawanRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/merchandise': typeof MerchandiseRoute
  '/mitra': typeof MitraRoute
  '/relawan': typeof RelawanRoute
  '/tentang-kami': typeof TentangKamiRoute
  '/demo/store': typeof DemoStoreRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/merchandise'
    | '/mitra'
    | '/relawan'
    | '/tentang-kami'
    | '/demo/store'
    | '/demo/tanstack-query'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/merchandise'
    | '/mitra'
    | '/relawan'
    | '/tentang-kami'
    | '/demo/store'
    | '/demo/tanstack-query'
  id:
    | '__root__'
    | '/'
    | '/merchandise'
    | '/mitra'
    | '/relawan'
    | '/tentang-kami'
    | '/demo/store'
    | '/demo/tanstack-query'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MerchandiseRoute: typeof MerchandiseRoute
  MitraRoute: typeof MitraRoute
  RelawanRoute: typeof RelawanRoute
  TentangKamiRoute: typeof TentangKamiRoute
  DemoStoreRoute: typeof DemoStoreRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tentang-kami': {
      id: '/tentang-kami'
      path: '/tentang-kami'
      fullPath: '/tentang-kami'
      preLoaderRoute: typeof TentangKamiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relawan': {
      id: '/relawan'
      path: '/relawan'
      fullPath: '/relawan'
      preLoaderRoute: typeof RelawanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mitra': {
      id: '/mitra'
      path: '/mitra'
      fullPath: '/mitra'
      preLoaderRoute: typeof MitraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merchandise': {
      id: '/merchandise'
      path: '/merchandise'
      fullPath: '/merchandise'
      preLoaderRoute: typeof MerchandiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/store': {
      id: '/demo/store'
      path: '/demo/store'
      fullPath: '/demo/store'
      preLoaderRoute: typeof DemoStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MerchandiseRoute: MerchandiseRoute,
  MitraRoute: MitraRoute,
  RelawanRoute: RelawanRoute,
  TentangKamiRoute: TentangKamiRoute,
  DemoStoreRoute: DemoStoreRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
